version: '3'
services:
  info-polus-task:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - APP_PORT=8080
    logging:
      driver: json-file
    restart: always
